#!/bin/bash

file="Global Rackspace V25.gpscript"

# Function list
functions=(
Wait Trace DebugCrash TraceActiveScope GetSnapshotPath GetSpaces PadInt SplitString SetChannelState 
GetCountInDurationMS UpdateSubbarLEDs GetParamIdxByName IsNPConfigParam CheckBlock CaptureFactoryDefaults 
ResetState GetFirstActiveScope TraceForensicChannelDump CycleGlobalSystemMode RefreshDiagDisplay 
ScrollToCurrentChannel RefreshVstInfoDisplay RefreshSafeReplacerUI ParkFadersForVST RestoreFadersForVST 
GetNoteName GetScaleKeyName GetScaleTypeName GetMusicTheoryString GetLuxusLabel TraceHardwarePrediction 
UpdateInjectionSplitDisplay UpdateInjectionFadeDisplay UpdateInjectionFilterDisplay UpdateInjectionNPDisplay 
UpdateInjectionTransposeDisplay UpdateVstInfoDisplay GetPrimaryVSTForChannel UpdateUsageLabelDisplay 
UpdateScopeVelocityMeter UpdateInjectionSoloDisplay UpdateInjectionMuteDisplay IsChannelActiveForLooper 
GetActiveLooperScope GetLoopActionName GetLoopLengthName GetLoopOutName GetLoopStopName RefreshLooperInfoDisplay 
TraceLooperDiagnostic RefreshLooperConfigDisplay ClearLooperArrays GetLoopProgressString BuildLooperConfigLines 
UpdateInjectionLooperTransportUI TraceTimeDomains UpdateInjectionLooperDisplay RefreshAllInjectionDisplays 
ExecuteSmartBypass AnalyzeChannel UpdateMetaColors SyncInputFeedback Trigger_NotesOff CloseLooperBuffer 
ValidateLooperScopeConfig CycleChannelScope CycleLoopLength CycleLoopAction RefreshCtrlInfoDisplay ShowCtrlOverlay 
CycleLoopTarget CycleLoopOutMode CycleLoopStopMode GetActiveMapSlot ScrollToCurrentVST SafeLoadPreset 
GetStoredPreset InjectKBSplitToggle InjectFilterToggle InjectTranspose InjectUserMuteToggle 
HandleInjectBypassClick IsChannelCustom IsChannelFactory ResetChannelToStandard ResetPluginParams 
ResetMidiInParams ResetFilterParams ArePluginParamsEqual AreMidiParamsEqual CopyPluginParams CopyMidiParams 
GetHardwareLabel GetAssignedHWString GetLinkNameHelper ScrollToCurrentCtrlScope BuildRecDisplayLines 
RefreshRecDisplay ShowVSTOverlay ShowRecOverlay ScrollToCurrentTimelineEvent GetChannelForVST GetStandardCCName 
ExecuteLink TriggerMacroFeedback UpdateControllerInfoDisplay UpdateEditScopeDisplay CycleEditScope 
IsBlockNameValid AppendLinkEncoded CaptureRechBaseline UpdateMidiConfigLabel UpdateMasterLabels UpdateChannelFade 
SaveHardwareMap LoadHardwareMap AssignHardware UnlearnHardware ApplyEditorTest ProcessMidiLearn UpdateSyncLabel 
CycleSyncMode CyclePluginPreset GetSysexString ClickWidget GetChordProFile UpdateTagInLine 
CalculateEffectiveTranspose StartMacroAnimation TriggerStyleAction UpdatePrompter JoinStringArray TrimAndClean 
IsDigitsOnly ExtractTagValue MyToUpper HasRealLyrics GetNoteIndex TransposeNote TransposeChordContent 
TransposeLine BuildZebraBlocks RecordTimelineEvent RecalculateTextDisplay TriggerNextSongPart SyncKBSplitWatchdog 
SyncMatrixToScriptlet UpdateCFConfigLabel ApplyCrossfade SyncRechUI TriggerSongTextLoad HexCharToInt IntToChar 
DecodeSysExName SanitizeAndSlugify LoadMappingFile AppendToMappingFile AddNewMapping GetBodyFromFile 
GetConfigFromFile GetDynamicStandardMap ValidateMapping ResetHardwareFadersForVST LoadControllerMap 
EvaluateSmartAdapt ApplyVstFocusBypass SyncChannelScopeToVst EvaluateAutoSysMode UpdateSoloMuteState 
ChangeVstScope GetLooperEventCount SendProgramChangeToVst TriggerVstPresetChange TriggerFocusLooperTransport 
RecordLoopEvent InjectLooperEvent ProcessLooperPlayback FeedLooper_Note FeedLooper_CC GetLoopModeName 
RefreshCtrlMapList CycleCtrlMap SyncGenosToCurrentMap ExecuteHardwareMacro ProcessHardwareCC AutoSwitchMapOnBypass 
MorphSend CaptureSmartRanges ExportSmartConfig CycleRechPresets CycleChannelUsage CycleScopeSection 
SetDefaultChannelScope ScanGlobalInstruments SmartLoadPresetAfterReplace BuildFilteredVstList 
SyncBrowserToLoadedPlugin FocusBrowserOnCurrentSlot RebuildBrowserStateAfterReboot AddJobToQueue SuperCleanPath 
ContinueActualReplace FireActualReplace TriggerNextQueueJob ExecuteVSTReplace GetPathForVst DeactivateChannel 
PerformSystemReset IsHeaderLine IsChordLine RemoveInlineComments AutoTagSections IsTabLine IsJunkLine 
CleanChordName WeaveChords GetEffectiveLength GetSmartWrapIndex FlushSection WashClipboardText ExecuteScrub 
CleanAndNormalizeRAM AnalyzeStructure ResetData JumpToRegMemAnchor CheckRegMemAutopilot FinishRecording 
ParseSongData CreateSkeletonFile LoadSongText LoadVstDatabase SaveSongSnapshot LoadSongTimeline 
LoadSongSnapshot SwitchToSongByName_Safe SaveStructureFromClipboard RefreshVstArray ProcessTopQueueJobResult 
FireGenosTransportEcho EvaluateTransportSync FireDirectGenosTransport PreviewActiveControllerMaps InjectNPToggle 
InjectNPStep ProcessSystemNavigation ProcessHardwareNote
)

# Sample a few to see pattern
for func in "DebugCrash" "TraceForensicChannelDump" "RefreshDiagDisplay"; do
    echo "=== $func calls ==="
    grep -n "^Function $func" "$file"
    grep " $func(" "$file" | grep -v "^Function" | head -3
    echo
done

